# Generated by Django 4.2.13 on 2024-07-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/creators'),
        ),
    ]
