# Generated by Django 4.2.13 on 2024-07-02 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0002_alter_creator_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='creator',
            name='image',
            field=models.ImageField(default='images/person.jpg', upload_to='uploads/creators'),
        ),
    ]
